/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionary;

import static dictionary.Dictionary.DumpData;

/**
 *
 * @author moham
 */
public class FrenchToEnglish extends javax.swing.JFrame {

    static Data X;
    
    static WELCOME W;
    /**
     * Creates new form FrenchToEnglish
     */
    public FrenchToEnglish(Data X,WELCOME W ) {
        
        initComponents();
                this.setTitle("FRENCH TO ENGLISH");

        this.setSize(716,433);
        
         this.X=X;
         this.W=W;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrenchWord = new javax.swing.JTextField();
        EnglishMeaning = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        FrenchWord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FrenchWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrenchWordActionPerformed(evt);
            }
        });
        getContentPane().add(FrenchWord);
        FrenchWord.setBounds(30, 180, 178, 44);

        EnglishMeaning.setBackground(new java.awt.Color(255, 255, 255));
        EnglishMeaning.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        EnglishMeaning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EnglishMeaning.setOpaque(true);
        getContentPane().add(EnglishMeaning);
        EnglishMeaning.setBounds(230, 180, 395, 118);

        Type.setBackground(new java.awt.Color(255, 255, 255));
        Type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Type.setOpaque(true);
        getContentPane().add(Type);
        Type.setBounds(30, 230, 178, 56);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter the French word here. ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 150, 178, 27);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 310, 59, 29);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(490, 310, 59, 29);

        Back.setText("← Back");
        Back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(20, 20, 84, 17);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dictionary/frenchflag(1).jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 720, 403);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FrenchWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrenchWordActionPerformed
        
        FrenchWord.setText("");
    }//GEN-LAST:event_FrenchWordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // System.out.println("Inserted Words: "+X.FR.countInserted);
         
         if(FrenchWord.getText().isEmpty()){
                      EnglishMeaning.setText("<html>"+"Please enter a word."+"</html>");

         }
         else{
             
             String FW=FrenchWord.getText().trim().toLowerCase();
             
             Node M=X.FR.searchFW(FW);
             
             String EM=M.EnglishMeaning;
             String T=M.Type;
             
            
             
             
             
         EnglishMeaning.setText("<html>"+EM+"</html>");
         
         Type.setText(T);

         }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        FrenchWord.setText("");
                EnglishMeaning.setText("");
                        Type.setText("");


    }//GEN-LAST:event_jButton2ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed

        this.setVisible(false);
        W.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrenchToEnglish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrenchToEnglish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrenchToEnglish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrenchToEnglish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrenchToEnglish(X, W).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel EnglishMeaning;
    private javax.swing.JTextField FrenchWord;
    private javax.swing.JLabel Type;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
